// Generated by CoffeeScript 1.8.0
(function() {
  var ProductCtrl;

  ProductCtrl = require("./../ctrl/productCtrl");

  ProductCtrl.productList(null, null, null, "2015-02", null, function(err, res) {
    return console.log(err, res);
  });

}).call(this);
